language: python
python:
  - "2.7"
os:
  - linux
branches:
  only:
    - master
compiler:
  - gcc
sudo: required
dist: trusty

install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo python setup.py install --neuron
script:
  - python2.7 test.py --all
  - python2.7 -c "import neuron"
