language: python
os:
  - linux
branches:
  only:
    - master
compiler:
  - gcc
sudo: required
dist: trusty
install:
  # - sudo python setup.py install --neuron --full-dependencies
  - sudo python setup.py install --full-dependencies
script:
  - nose2
  # - python2.7 -c "import neuron"
