language: python
python:
  - "2.7"
os:
  - linux
branches:
  only:
    - master
compiler:
  - gcc
sudo: required
dist: trusty
services: docker
before_install:
    - docker build -t uncertainpy -f Dockerfile .
# before_script:
#   - "export DISPLAY=:99.0"
#   - "sh -e /etc/init.d/xvfb start"
#   - sleep 3 # give xvfb some time to start
script:
    - docker run uncertainpy python test.py --fast
