sudo: required
services: docker
language: python
python:
- '2.7'
# install:
#  - pip install codecov
# before_script:
#  - docker build -t uncertainpy -f .docker/Dockerfile_python2 .docker
# #  - docker build -t uncertainpy -f .docker/dummy .docker
script:
- echo Not running tests
# - docker run -v $(pwd):/home/docker/uncertainpy -t uncertainpy /bin/bash /home/docker/uncertainpy/.docker/run_tests.sh
# after_success:
# - codecov
deploy:
  provider: pypi
  user: simetenn
  password:
    secure: fheAXUi5KGfLmeAdJ0q84nh66j8NzwcQMmBmNDVFfYUqVTDSwJNrPPylMV2TBbkgbe2XFkQbMumhalNxXqZ390nxXb5NnH1dMfSDvb4hocz1HrCDo8BrN2SJe59nGlduOhpnXDJwpPf9CtqAWQScvq7NRuUkpAXFsDi+xMaMJwoOu1Tv6rbF2bEybnzmGjoGdN3DW78O3r9jBQ7WhAX+MRKRl3RQVXp9yZkKx+FMP6Xu5JoLFhNeSSO5zVO57lQM2aze6JNCXyBW1zXBb6eCXzPU0welOjbnWpO1jxJzPuYA0nufm2Q2YgVDMRmKESIzi2Z1K1Z8VKDUTQV21r2cC95qol3J4VppsntNcQMScchLOIr7uJMvuOzwxjB60emP3t4pWwF5dAgfvJuKF1UVl9p9c7Ijt+XeyWt9R0aNHfXt6MwiW6ymdhoCCSc/H5EujzGN1zxVUzoiI7m4mTJmGR3OtSxq9VbjoJ8O+VKNH22/GdG9UngP8iUuSou/ZvviKnGDl9hVuxquA7lAjFiAy0ydjM1uw/flGPDJnK6F2U35vEnb6dFrd+nm6uU5kyj/l1wMQ+IESyAATSjlQGKeBhGSYx7LsGUWAEH0hoGv6PXSnUusUGIuRDnRHENrqBe1opVIgAQL9hEhYxrQbUpuJYorgAC9GdCgvsTbqoQo6oo=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: simetenn/uncertainpy
