language: python
os:
  - linux
branches:
  only:
    - master
compiler:
  - gcc
sudo: required
dist: trusty

install:
  # - sudo python setup.py install --neuron --full-dependencies
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo python setup.py install --full-dependencies
script:
  - workon uncertainpy
  - python testrunner.py
  # - python2.7 -c "import neuron"
