sudo: required
services: docker
language: python
python:
- '2.7'
# install:
#  - pip install codecov
# before_script:
#  - docker build -t uncertainpy -f .docker/Dockerfile_python2 .docker
# #  - docker build -t uncertainpy -f .docker/dummy .docker
script:
- echo Not running tests
# - docker run -v $(pwd):/home/docker/uncertainpy -t uncertainpy /bin/bash /home/docker/uncertainpy/.docker/run_tests.sh
# after_success:
# - codecov
deploy:
  provider: pypi
  user: simetenn
  password:
    secure: E9iQH8dEO1siALTMgRdPGO8ofj3w/9rjbMYpdUN8RkT/CjWV4Yj1lZXYBuIC40C3rhNyB3KRr6KlOGucvcGjS/Ob7vhYzhR6r4PERNeF57r4RjOMOgN+dTNWZaByVpyqmOOCHGNCLLaSvgE2vOAVFtmChgS3zcAsWeP75wpvf9bAQv1P+rEa3RDbgjS4dfmLzeAuxHphKSrKUYcTrcU5/cwhyLHW4YknPRwrEJ/BaWNn13lVp63kIGxzCU/HuVpPXuGyKHiSruvgXNw7SI2FWQ9n078FJzX6AU7LNoJXH8GfNlV/wgkCYDTmpeOzU4vnmemCFDl+F2Zj4qmKWP/s8i2QBZncx1dHU4BXl5EuSJfOr+8hcCgR2zGGg/gCl0eGVfFUHJwPDXk9G6m+PZc/E7t6M/BD+Gk8Pf47U6uTSF1LayJ2MUhnAH2Icc5v/b4sjN+uCqXfIl4drHMt2F/izG4La6N1H42STTaE14jIxETZJhqxQuwZdzmUAcU/I+vo/r1VYY2RIeVGaE1xrGwRQG/+YT0p2PoL58s9HMKR54VXaSWXrLedT8w6C1zuTT8fXNfMXb2A7V6MOQCOCW95cxIipmd3+6riNl0IHNBvW4nEURHP2TPxY2De2iwPlJoUw3/AywNJu1nvyQEUSxf6e+MHNmI0ZSzfYFlZdCbioeQ=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: simetenn/uncertainpy
