sudo: required
services: docker
language: python
python:
- '2.7'
before_script:
- docker build -t uncertainpy -f .docker/Dockerfile_python2 .docker
script:
- docker run -v $(pwd):/home/docker/uncertainpy -t uncertainpy /bin/bash uncertainpy/.docker/run_tests.sh
- bash <(curl -s https://codecov.io/bash)
deploy:
  branch: master
  provider: pypi
  user: simetenn
  password:
    secure: wWx5Gs4WWKNHbg1ICEl2Y/t9vKJaBRzB0ChIaY8c5CppSKDReyMsrjcss5s4aaPPPOjuVMMP1WnMHfyj61N6lFH3L66ZCBEz7Jeeu1S3bmFA5KHUs825RlP3jWLevyLxkVikSmopJ/GvJX0hdYTtchg3qGkF2bGvpZhQtLADLhttI9VMMrKn2myd4HLfGO+9uoa6+qF05tbuYetFagg4ZMBrOFmxEsny9rn+2Mgond7y2U0DuTB9trtDmCxvS+niGC4xqiVihBsFaIyxOGOVeuVtlPIaC8hGQbOkdhGjZclXrUxDbEAa2oIEKOXc0lGu1oIMthFG0q4GjYP/RR/WF7aPfQeb1C7448yBw1bPVVih9PzvqLAQYClzgpwC/Yrd83Gcx3D3FBZbJxB44hYtRIKh7WKuFS1N+FFeCgE4Kx12fz7blVVFAdxQFaDOGrtT0Vk9C5XHRnrxZhPBcoQEqBi4ftIODXP3buTdrNOdyMijRh57UsAeWC3yE6GIqMtxaoMUM1LzwlCbv4u3+gH5rTqkEFk7MZrn0WOdVpew9IZPkLc6Ia7mLwhdqIf9gRkox1Iydk0RZSdfl4n6IUb63Zc5HoPOWA42Ifwe4dTCov4J0P8Zbok+4fUmfl44RxBfzhSx09s/cdqlD8w4FoQ/l+9NkKFJGc3MQBCB+h0XTcM=
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    tags: true
