language: python
os:
  - linux
branches:
  only:
    - master
compiler:
  - gcc
sudo: required
dist: trusty
install:
  # - sudo apt-get install -y virtualenvwrapper
  # - sudo python setup.py install --neuron
  - sudo python setup.py install
script:
  # Currently travis does not support my creation of virtual env
  # - source /etc/bash_completion.d/virtualenvwrapper
  # - workon uncertainpy
  - nose2
  # - python2.7 -c "import neuron"
