language: python
python:
  - "2.7"
os:
  - linux
branches:
  only:
    - master
# compiler:
#   - gcc
sudo: false
dist: trusty
services: docker
before_install:
    - docker build -t uncertainpy -f .docker/Dockerfile_python2 .docker
# before_script:
#   - "export DISPLAY=:99.0"
#   - "sh -e /etc/init.d/xvfb start"
#   - sleep 3 # give xvfb some time to start
script:
    # - docker run -t uncertainpy /home/docker/simulators/bin/nest_vars.sh; python test.py --travis
    - docker run -v $(pwd):/home/docker/uncertainpy -t uncertainpy /bin/bash uncertainpy/travis.sh

    # - docker run -v $(pwd):/uncertainpy -t uncertainpy