sudo: required
services: docker
language: python
python:
  - "2.7"
  # - "3"
install:
  - pip install codecov
before_script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then PYTHON_VERSION=2 ; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3 ]]; then PYTHON_VERSION=3 ; fi
  - docker build -t uncertainpy$PYTHON_VERSION -f .docker/Dockerfile_python$PYTHON_VERSION .docker
  - docker build -t uncertainpy -f .docker/Dockerfile_uncertainpy$PYTHON_VERSION .docker
  - ci_env=`bash <(curl -s https://codecov.io/env)`
script:
  - docker run -t uncertainpy $ci_env cd uncertainpy; coverage run test.py all; coverage xml; bash <(curl -s https://codecov.io/bash)
# after_success:
#   - codecov
# before_deploy:
#   - sudo rm -rf src/uncertainpy.egg-info
deploy:
  provider: pypi
  user: simetenn
  skip_cleanup: true
  password:
    secure: jmuUgAq8ilrzQAa7e4gmsU7WKtoLK8rFHKdKUSrU9FNM1m7Ebk7uyY+n+TqXfVVwCeCMT9R9//oly7gbTK+JpkFcApYZhO5GMC1p5Ekn8ANeptk4zjbHQfcARsEcALgUDslZq9ZRwkPbOy97UA9ffJBeMam3xo2nPK+kq+pQv+hkHm0up4avPgXVIttiMplgVLsEEFyZ6vaLG9HZw/t+ddUvCYYL33MAHmtPCBm3bKWc8KON3hGHvKaOmXEQjGf4ylsYJoMwh6+8Q+5yiXOUT3SzLW8o8m99HHOCL81O1E5aJlgfcxW5Wpos95i0/q2s5BMXguWRuTG+2ZDBMt7BSFeOfeZluUxa0GOvNgc3IlBV8Mr5ZYzNgvqRD1KQyLqYxWhr7/EtcoZw0G3QrSsmCNPtH27SETeYuOzUJZ3Cg/hVYENMQIvLiIQ+NZhKlb+2a5apaWSvSPiUOSaDY62KZNJNhOvqZsdlAxj5GvXgVVEHlegoyziaOkg5KR52nxxKe7vgV/N8S3sJ8r3s8d0SrTsKd6r12alUkeiusei4vqAgRaGgdHotw/oaDOfOVFoRARL7hNh8VvkQXNoksRe7OFZZ8RUrC4AdwvkjoLwMw0BvrKIgH2O1amSdsOElpOp0Vth/oc2kak11uuu3HVM0o0/H9CB3yvR3GnmEj9o9jBI=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: simetenn/uncertainpy
