sudo: required
services: docker
language: python
python:
- '2.7'
# install:
#  - pip install codecov
# before_script:
#  - docker build -t uncertainpy -f .docker/Dockerfile_python2 .docker
# #  - docker build -t uncertainpy -f .docker/dummy .docker
script:
- echo Not running tests
# - docker run -v $(pwd):/home/docker/uncertainpy -t uncertainpy /bin/bash /home/docker/uncertainpy/.docker/run_tests.sh
# after_success:
# - codecov
deploy:
  provider: pypi
  user: simetenn
  password:
    secure: cc687bf9/ksPjQ+rTBYJI98TlSPzpclXl2mOaLjAPrTSY/AK5lfnT47Qw10X1oQIomiY/UWJG2J1OimBdSZykHiH3h7ogWt7eNI1P2x5B0ir5x2wEoZ0tOZf4PIP2o7XnhYqpABuO5DqC+Um6rNA0PZAhy9pgtKEqrzTWZPYwSWS8f1b6l4pRmm5KKAlAqYQdrdIlUJKoYg9k5jWzBiwmgUs27+vWVvuPPzolbSECT2OoDjPNWcbKqQLi0OFwdWcpT3sdNPljlrG0JhkuU61l5VhROu1p7jCoAhE+yO/6PFu2RwSnDqZe3XfHruqdltHGk8wqM23zx01e5aQpVGmdv+cf86zRNbmNNXNxfC/OpgibVfvcuy2nDuGeqv4ls9UJJh8TysDWS3mVssaHuD9YVwxAx8b+//ydc3NiCvgGBTae1MP+rZkoM47rbiMdcm1iFttCZByjF4tytUwWf5bQ/y1qgok8UmEmhF5dlvwxFUQ7+fsnNV3uWKVZCnAXQHM2oUVIdG7t3yUhKFWU/nWbBxGA2pmuSf7e9iy4lrVKMGNqR/vFG+tC4KcJrfKT3alCw2FLU5U7v5ioPgY3fowWfxwZQEvsN1wicUm7KOPjcN2fLpnX2pg7Ss8OZIlxoiT3yU0Tk9a0tF4sWnS1jypOGOvRIW96oao4FoS/coa660=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: simetenn/uncertainpy
