language: python
os:
  - linux
branches:
  only:
    - master
compiler:
  - gcc
sudo: required
dist: trusty
install:
  - sudo python setup.py install
script:
  - source /etc/bash_completion.d/virtualenvwrapper
  - workon uncertainpy
  - nose2
