sudo: required
services: docker
language: python
python:
  - "2.7" # Placeholder only
  - "3.6" # Placeholder only
install:
  - pip install codecov
before_script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then PYTHON_VERSION=2 ; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then PYTHON_VERSION=3 ; fi
  - docker build -t python$PYTHON_VERSION -f .docker/Dockerfile_python$PYTHON_VERSION .
  - docker build -t uncertainpy -f .docker/Dockerfile_uncertainpy$PYTHON_VERSION .
  - ci_env=`bash <(curl -s https://codecov.io/env)`
script:
  - docker run $ci_env -t uncertainpy uncertainpy/run_tests.sh
# before_deploy:
#   - sudo rm -rf src/uncertainpy.egg-info
deploy:
  provider: pypi
  user: simetenn
  skip_cleanup: true
  password:
    secure: u6g+yaBmkTSbAtOpdSAlNxJ6eBNg2Uv80aNmdP9pcqZacM9R29EFJ3gwG7Nc/PAPmB32l7eZ6cuqZZXrDbIQVz5VQyjm5O3PznHNXtzi+wILvZ2nEiYkLfPHm3BfCbSk05De7/jaYSwZLJe3ldihEa0DHVsqtlYh/meew0QyVSdTgjlIX6Wh7paafwLC6yBQODEzC3aFN0SyuqgvTBvcTysIlMcyxZmWewIlH3/HBJq0t2a11NR450Zb291bcK2/QtruLCRzerGeAdcQm+TLrOJxET5lU2Xv6nbHgE9HH8/2gfYasWFe4exAsggP2ZTC46eCuovZlo8PRXnN8KXp1HCS5ao+LQ6+L14jmi5aDaGiXz2GmwdOv7wzmSj0aVgfc5WN3AbA4K3FULoG7aSadsXtZj0olgVV1CNeoSHZ/oPa48ix1wMqgRf4j0B1E/2MJOiB7Bnwk8bdhIHQ/TgAZwsawS7RCwJbwWXV5G7E3cA4WKNC+rtPZVwp0L/PhlfbWlorf3Xsff61+Xthq6oXSBMD8HHxglXShI4Xsv+9/uizFAe3vShYEyKF+8ZHrlpv3MC40HPgBLpB4LT802PTELK3qqtJhP6q/rqKZdd3VIQ9SWF6saaiJVVQ2pNcyaDCivsA3xZUBLX5g5KpU1zuizf678CYq1bWdbUxNGc3pa4=
  on:
    python: 3.6
    tags: true
    distributions: sdist bdist_wheel
    repo: simetenn/uncertainpy
