language: python
python:
  - "2.7"
os:
  - linux
branches:
  only:
    - master
compiler:
  - gcc
sudo: required
dist: trusty

install:
  # - sudo python setup.py install --neuron --full-dependencies
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo ./uncertainpy/install_scripts/install_virtual.sh
  - mkvirtualenv test
  - workon test
  - sudo python setup.py install --virtual --neuron
script:
  - workon uncertainpy
  - python2.7 test.py --all
  # - python2.7 -c "import neuron"
