language: python
python:
  - "2.7"
os:
  - linux
branches:
  only:
    - master
compiler:
  - gcc
sudo: required
dist: trusty
services: docker
before_install:
    - docker build -t simetenn/uncertainpy -f Dockerfile .
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
    - docker run simetenn/uncertainpy python2.7 test.py --fast
  #- python2.7 test.py --all
  # - python2.7 -c "import neuron"
