version : 1
disable_existing_loggers: True
formatters:
  uncertainpy_formater:
    '()': uncertainpy.utils.MyFormatter
handlers:
  tqdm:
    class: uncertainpy.utils.TqdmLoggingHandler
    formatter: uncertainpy_formater
  multiproccess_file:
    class: uncertainpy.utils.MultiprocessLoggingHandler
    formatter: uncertainpy_formater
    filename: uncertainpy.log
    mode: w
loggers:
  uncertainpy:
    handlers: [tqdm, multiproccess_file]
    propagate: True
