package:
  name: uncertainpy
  version: 0.9

source:
  path: ..

build:
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - numpy
    - scipy
    - quantities
    - xvfbwrapper
    - chaospy
    - tqdm
    - h5py
    - multiprocess
    # Plotting dependencies
    - matplotlib
    - seaborn
    # Spiking feature dependencies
    - efel
    # Network feature dependencies
    - elephant
    - python-neo
    - quantities


test:
  source_files:
    - uncertaipy/tests
    - docs
    - examples
  requires:
    - pytest
    - sphinx
  imports:
    - uncertainpy
  commands:
    - python test.py --travis
    - cd docs ; make doctest

about:
  home: https://github.com/simetenn/uncertainpy
  # license: GPLv3
  # license_file: LICENSE